### ISSUE TITLE
Morning session: Peer-to-peer code review 08.06.2021

### ISSUE THREAD

**Issue by Felipeg005** [Felipeg005/Capstone-html-css-Javascript#2]
Thank you for seeing my code, I wait for your recommendations. :+1:

**Comment by zainsadaqat** [comment]
Great Job @Felipeg005  👍🏻 💯 

Your code is clean and the project is looking great for both mobile and desktop views. 🥇 😄

**Comment by rotimiazeez** [comment]
Hello @Felipeg005 👋🏽, 
You have a good clean and sematic project here 👍🏽, all I have to say is you are good to go 🚀. This is a gem 💯
